import Head from 'next/head'
import { Inter } from 'next/font/google'
import Introduce from "@/components/introduce/introduce";
import Header from "@/components/header";
import Skills from "@/components/skill/skills";
import Projects from "@/components/project/projects";
import Profile from "@/components/profile/profile";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>tw-portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <Header/>
                <Introduce/>
                <Profile/>
                <Skills/>
                <Projects/>
            </main>
        </>
    )
}
